import LetterInput from "./LetterInput";

export default function PlayerScoreInput(props) {
    return (
        <div>
            <LetterInput 
                letterId="letter1"
                dWordId="dWord1"
                tWordId="tWord1"
            />
            <LetterInput 
                letterId="letter2"
                dWordId="dWord2"
                tWordId="tWord2"
            />
            <LetterInput 
                letterId="letter3"
                dWordId="dWord3"
                tWordId="tWord3"
            />
            <LetterInput 
                letterId="letter4"
                dWordId="dWord4"
                tWordId="tWord4"
            />
            <LetterInput 
                letterId="letter5"
                dWordId="dWord5"
                tWordId="tWord5"
            />
            <LetterInput 
                letterId="letter6"
                dWordId="dWord6"
                tWordId="tWord6"
            />
            <LetterInput 
                letterId="letter7"
                dWordId="dWord7"
                tWordId="tWord7"
            />
            <LetterInput 
                letterId="letter8"
                dWordId="dWord8"
                tWordId="tWord8"
            />
            <LetterInput 
                letterId="letter9"
                dWordId="dWord9"
                tWordId="tWord9"
            />
            <LetterInput 
                letterId="letter10"
                dWordId="dWord10"
                tWordId="tWord10"
            />
        </div>
    )
}