import LetterInput from "./LetterInput";
// would like to refactor to make this more concise
export default function PlayerScoreInput(props) {
    return (
        <div>
            <LetterInput 
                letterId="letter1"
                dLetterId="dLetter1"
                tLetterId="tLetter1"
                name="doubleTriple1"
            />
            <LetterInput 
                letterId="letter2"
                dLetterId="dLetter2"
                tLetterId="tLetter2"
                name="doubleTriple2"
            />
            <LetterInput 
                letterId="letter3"
                dLetterId="dLetter3"
                tLetterId="tLetter3"
                name="doubleTriple3"
            />
            <LetterInput 
                letterId="letter4"
                dLetterId="dLetter4"
                tLetterId="tLetter4"
                name="doubleTriple4"
            />
            <LetterInput 
                letterId="letter5"
                dLetterId="dLetter5"
                tLetterId="tLetter5"
                name="doubleTriple5"
            />
            <LetterInput 
                letterId="letter6"
                dLetterId="dLetter6"
                tLetterId="tLetter6"
                name="doubleTriple6"
            />
            <LetterInput 
                letterId="letter7"
                dLetterId="dLetter7"
                tLetterId="tLetter7"
                name="doubleTriple7"
            />
            <LetterInput 
                letterId="letter8"
                dLetterId="dLetter8"
                tLetterId="tLetter8"
                name="doubleTriple8"
            />
            <LetterInput 
                letterId="letter9"
                dLetterId="dLetter9"
                tLetterId="tLetter9"
                name="doubleTriple9"
            />
            <LetterInput 
                letterId="letter10"
                dLetterId="dLetter10"
                tLetterId="tLetter10"
                name="doubleTriple10"
            />
        </div>
    )
}